import {Dimensions, Platform} from 'react-native';
import {RFValue} from 'react-native-responsive-fontsize';

export const {height: HEIGHT, width: WIDTH} = Dimensions.get('window');
// Design Screen
const DeviceHeightAid = 1200;

const Constants = {
  debugMode: true,
  // Keys
  GoogleAPIKey: '',
  // Responsive Size
  ResponsiveSize: {
    f1: RFValue(1, DeviceHeightAid),
    f2: RFValue(2, DeviceHeightAid),
    f3: RFValue(3, DeviceHeightAid),
    f4: RFValue(4, DeviceHeightAid),
    f5: RFValue(5, DeviceHeightAid),
    f6: RFValue(6, DeviceHeightAid),
    f7: RFValue(7, DeviceHeightAid),
    f8: RFValue(8, DeviceHeightAid),
    f9: RFValue(9, DeviceHeightAid),
    f10: RFValue(10, DeviceHeightAid),
    f11: RFValue(11, DeviceHeightAid),
    f12: RFValue(12, DeviceHeightAid),
    f13: RFValue(13, DeviceHeightAid),
    f14: RFValue(14, DeviceHeightAid),
    f15: RFValue(15, DeviceHeightAid),
    f16: RFValue(16, DeviceHeightAid),
    f17: RFValue(17, DeviceHeightAid),
    f18: RFValue(18, DeviceHeightAid),
    f19: RFValue(19, DeviceHeightAid),
    f20: RFValue(20, DeviceHeightAid),
    f21: RFValue(21, DeviceHeightAid),
    f22: RFValue(22, DeviceHeightAid),
    f23: RFValue(23, DeviceHeightAid),
    f24: RFValue(24, DeviceHeightAid),
    f25: RFValue(25, DeviceHeightAid),
    f26: RFValue(26, DeviceHeightAid),
    f27: RFValue(27, DeviceHeightAid),
    f28: RFValue(28, DeviceHeightAid),
    f29: RFValue(29, DeviceHeightAid),
    f30: RFValue(30, DeviceHeightAid),
    f31: RFValue(31, DeviceHeightAid),
    f32: RFValue(32, DeviceHeightAid),
    f33: RFValue(33, DeviceHeightAid),
    f34: RFValue(34, DeviceHeightAid),
    f35: RFValue(35, DeviceHeightAid),
    f36: RFValue(36, DeviceHeightAid),
    f37: RFValue(37, DeviceHeightAid),
    f38: RFValue(38, DeviceHeightAid),
    f39: RFValue(39, DeviceHeightAid),
    f40: RFValue(40, DeviceHeightAid),
    f41: RFValue(41, DeviceHeightAid),
    f42: RFValue(42, DeviceHeightAid),
    f43: RFValue(43, DeviceHeightAid),
    f44: RFValue(44, DeviceHeightAid),
    f45: RFValue(45, DeviceHeightAid),
    f46: RFValue(46, DeviceHeightAid),
    f47: RFValue(47, DeviceHeightAid),
    f48: RFValue(48, DeviceHeightAid),
    f49: RFValue(49, DeviceHeightAid),
    f50: RFValue(50, DeviceHeightAid),
    f51: RFValue(51, DeviceHeightAid),
    f52: RFValue(52, DeviceHeightAid),
    f53: RFValue(53, DeviceHeightAid),
    f54: RFValue(54, DeviceHeightAid),
    f55: RFValue(55, DeviceHeightAid),
    f56: RFValue(56, DeviceHeightAid),
    f57: RFValue(57, DeviceHeightAid),
    f58: RFValue(58, DeviceHeightAid),
    f59: RFValue(59, DeviceHeightAid),
    f60: RFValue(60, DeviceHeightAid),
    f61: RFValue(61, DeviceHeightAid),
    f62: RFValue(62, DeviceHeightAid),
    f63: RFValue(63, DeviceHeightAid),
    f64: RFValue(64, DeviceHeightAid),
    f65: RFValue(65, DeviceHeightAid),
    f70: RFValue(70, DeviceHeightAid),
    f77: RFValue(77, DeviceHeightAid),
    f78: RFValue(78, DeviceHeightAid),
    f84: RFValue(84, DeviceHeightAid),
    f98: RFValue(98, DeviceHeightAid),
    f99: RFValue(99, DeviceHeightAid),
    f113: RFValue(113, DeviceHeightAid),
    f100: RFValue(100, DeviceHeightAid),
    f120: RFValue(120, DeviceHeightAid),
    f130: RFValue(130, DeviceHeightAid),
    screenHeight: HEIGHT,
    screenWidth: WIDTH,
  },
};

export default Constants;
